# Generated by Django 3.0 on 2019-12-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='study_nurse_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
