# Generated by Django 3.0 on 2019-12-25 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth',
            field=models.DateField(default=datetime.date(1900, 12, 31)),
        ),
    ]
